# Generated by Django 4.1.6 on 2023-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_token', models.CharField(blank=True, max_length=300, null=True)),
                ('email_token', models.CharField(blank=True, max_length=300, null=True)),
                ('expiration', models.DateTimeField()),
                ('phone_change_successfull', models.BooleanField(default=False)),
                ('email_change_successfull', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'changed user',
                'verbose_name_plural': 'changed users',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=6)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP code',
                'verbose_name_plural': 'OTP codes',
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('token', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
                ('expiration', models.DateTimeField()),
                ('phone_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
