# Generated by Django 4.1.6 on 2023-02-27 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('old_email', models.CharField(blank=True, max_length=100, null=True)),
                ('new_email', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=300)),
                ('expiration', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 27, 4, 27, 43, 374480, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'email change otp code',
            },
        ),
        migrations.DeleteModel(
            name='EmailChangeOtp',
        ),
    ]
