# Generated by Django 4.1.6 on 2023-02-28 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_changeduser_delete_emailchangeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeduser',
            name='expiration',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 28, 15, 47, 19, 269365, tzinfo=datetime.timezone.utc)),
        ),
    ]
