# Generated by Django 4.1.6 on 2023-02-28 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_changeduser_user_id_alter_changeduser_expiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeduser',
            options={'verbose_name': 'changed user', 'verbose_name_plural': 'changed users'},
        ),
        migrations.AddField(
            model_name='changeduser',
            name='email_change_successfull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changeduser',
            name='phone_change_successfull',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='changeduser',
            name='expiration',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 28, 17, 11, 22, 956221, tzinfo=datetime.timezone.utc)),
        ),
    ]
