# Generated by Django 4.1.6 on 2023-03-02 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_changeduser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeduser',
            name='token',
        ),
        migrations.AddField(
            model_name='changeduser',
            name='email_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='changeduser',
            name='phone_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='changeduser',
            name='expiration',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 2, 12, 55, 8, 353474, tzinfo=datetime.timezone.utc)),
        ),
    ]
