# Generated by Django 4.1.6 on 2023-03-02 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_changeduser_token_changeduser_email_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeduser',
            name='expiration',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 2, 12, 48, 35, 450679, tzinfo=datetime.timezone.utc)),
        ),
    ]
