# Generated by Django 4.1.6 on 2023-03-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_changeduser_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeduser',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
